### PR TITLE
Git clone feature

### PR DESCRIPTION
**Pull request by Grafikart**
I added the ability to clone project from github using the git command line (the git clone command is used instead of classic download if the ".git" pattern is detected in the URL).

My code is a bit dirty cause I don't know Python language but I think the feature could be interesting to update library quickly using git pull afterward.

### CODE REVIEW

**Comment by weslly** [comment]
You can get the latest version of github repositories by adding the link to download it as zip in your settings (e.g. https://github.com/cakephp/cakephp/zipball/master )

**Comment by Grafikart** [comment]
Yes but sometimes I use my own repository or a fork where I do some push/commit :)

But this is not an important feature :)

**Comment by weslly** [comment]
I'll keep this issue open and implement it on the upcoming minor updates :)

(I can't merge your code right now because you didn't use threads so when the plugin is performing a "git clone" the editor becomes unresponsive until the operation is done)

**Comment by sindresorhus** [comment]
Any updates? This would be very useful.

**Comment by weslly** [comment]
@sindresorhus I'll add this feature in the next update.

**Comment by sindresorhus** [comment]
:)

**Comment by Grafikart** [comment]
No news from maintainer I close this PR

**Comment by sindresorhus** [comment]
@Grafikart Lol. Because of https://twitter.com/sindresorhus/status/780105339639304196, right? :p

**Comment by Grafikart** [comment]
@sindresorhus yeah I'm easily influenced :)

**Pull request closed without merging**
