### PR TITLE
Support Sublime Text 3

### PR DESCRIPTION
**Pull request by gnarula**
Works fine on my end (using Arch Linux x86-64 and Sublime Text Build 3010) using wget. ST3 build for linux doesn't include SSL so that portion remains untested.

The only change I introduced is creating a new file for "Single File" downloads as opposed to replacing the selected text previously.

Regards,
Gaurav

### CODE REVIEW

**Comment by haimich** [comment]
Works in my setup (Linux, Sublime Build 3012)...thanks for your work!

**Comment by weslly** [comment]
Thanks for the PR. It seems to work fine but I still need to test it in ST2.

**Comment by gnarula** [comment]
the st3 branch won't work in ST2 (hence the different branch) since st3 uses Python 3.3.

**Comment by weslly** [comment]
I've created a new branch for st3, can you open a new pull request to it instead of `master`?

**Pull request closed without merging**
