### PR TITLE
Added .tar/.tar.gz file handling

### PR DESCRIPTION
**Pull request by krollster**
Hi Weslly,

Installed your plugin recently and loved it. I've added package handling for .tar/.tar.gz archives. Not sure how busy you are at the moment, but maybe you could have a look and see if it's worth adding to the master.

cheers,
Ben

### CODE REVIEW

**Comment by zchrykng** [comment]
Would it be useful to refactor the code in general?

I am thinking something along the lines of making an abstract class that defines the interface and common code, and then creating a class to handle each type. This would make it fairly trivial to add more handlers. I would be willing to take a shot at it if people are interested.

**Comment by krollster** [comment]
Sounds like a good idea. I'm not sure what other archives types people would want to fetch since I mainly work with web related stuff and some Python now and then, but having the option to easily add more types can't hurt.

**Comment by zchrykng** [comment]
I didn't have anything in mind but I was didn't like the code duplication.
I guess you could have it fetch from git repos or such.

On Apr 26, 2013, at 5:45 PM, Benjamin Kroll notifications@github.com
wrote:

Sounds like a good idea. I'm not sure what other archives types people
would want to fetch since I mainly work with web related stuff and some
Python now and then, but having the option to easily add more types can't
hurt.

—
Reply to this email directly or view it on
GitHubhttps://github.com/weslly/Nettuts-Fetch/pull/29#issuecomment-17101994
.

**Comment by krollster** [comment]
I had the tar/gz functionality integrated with the existing zip handling code to start with, but it got quite messy adding conditionals all over the place to handle the differences between the two archive types (path indentifiers, file access etc) which is why i split them up into two separate methods.
There's still a fair amount of duplication though I agree.

Looking at the python docs 2.7.x provides for zlib, gzip, b2z, zip and tar maybe Weslly could run a poll or feature request to see what people actually would want to fetch and decompress?

**Comment by krollster** [comment]
Please disregard this pull request, utter rubbish I committed here. Will fix and re-submit. Apologies.

**Pull request closed without merging**
